config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'advertisements#index'
  get :dashboard, to: "pages#dashboard"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  resources :advertisements, only: [:index, :new, :create,:show, :edit, :update, :destroy] do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:destroy, :update] do
    get :accept_booking, to: "bookings#accept"
  end
    # resources :bookings, only: [:destroy]
  # root "articles#index"
end

app/models/advertisement.rb
class Advertisement < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :advertisement, optional: true
  belongs_to :user, optional: true

  validates :status, inclusion: { in: %w[accepte refuse], allow_nil: true }
  STATUSES = ["accepte", "refuse"]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :advertisements
  has_many :bookings

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def rentals
    bookings.map {|booking| booking.advertisement}
  end
end

app/controllers/advertisements_controller.rb
class AdvertisementsController < ApplicationController
  def index
    @advertisements = Advertisement.all
    @markers = @advertisements.geocoded.map do |advertisement|
      {
        lat: advertisement.latitude,
        lng: advertisement.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {advertisement: advertisement}),
        marker_html: render_to_string(partial: "marker")
      }
    end
  end
  
  def show
    @advertisement = Advertisement.find(params[:id])
  end

  def new
    @advertisement = Advertisement.new
  end

  def create
    @advertisement = current_user.advertisements.build(advertisement_params)
    if @advertisement.save
      redirect_to @advertisement, notice: "Annonce crée avec succès"
    else
      render :new
    end
  end

  def destroy
    @advertisement = Advertisement.find(params[:id])
    @advertisement.destroy
    redirect_to dashboard_path
  end

  private
  def advertisement_params
    params.require(:advertisement).permit(:title, :description, :price, :photo, :address)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_number, :age])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :password])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @advertisement = Advertisement.find(params[:advertisement_id])
    @booking = Booking.new
  end

  def create
    @advertisement = Advertisement.find(params[:advertisement_id])
    @booking = Booking.new(booking_params)
    @booking.advertisement = @advertisement
    @booking.user = current_user
    @booking.save
    if @booking.save!
      redirect_to dashboard_path(tab: "mes_annonces"), notice: 'Annonce créee avec succès.'
    else
      redirect_to advertisements_path, notice: 'Reservation was successfully declined.'
    end
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(params[:booking])
  end

  private

  def booking_params
    params.require(:booking).permit(:status, :total_price)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    @advertisements = Advertisement.all
  end

  def show
    @user = current_user
    @advertisements = current_user.advertisements
  end

  # def edit
  #   @advertisements = Advertisement.all
  # end

  # def update
  #   @advertisement = Advertisement.update(params[:id])
  #   if @advertisement.update(advertisement_params)
  #     redirect_to_dashboard_path(@dashboard)
  #   else
  #     render 'edit'
  #   end
  # end

  # def destroy
  #   @advertisement = Advertisement.find(params[:id])
  #   @advertisement.destroy
  #   redirect_to dashboard_path, notice: "Annonce supprimée avec succès.", status: :see_other
  # end

  private

  def advertisement_params
    params.require(:advertisement).permit(:title, :description, :price)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def dashboard
    @user = current_user
    @my_advertisements = current_user.advertisements
    @advertisements = current_user.rentals
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/advertisements/_form.html.erb
<%= simple_form_for @advertisement, url: advertisements_path, method: :post, local: true do |form| %>
  <%= form.input :title, label: "Titre" %>
  <%= form.input :description, label: "Description" %>
  <%= form.input :price, label: "Prix" %>
  <%= form.input :address, label: "Address",
    input_html: {data: {address_autocomplete_target: "adresse"}, class: "d-none"},
    wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}} %>
  <%= form.input :photo, label: "Photo", as: :file %>
  <div>
    <%= form.submit "Créer l'annonce" %>
  </div>
<% end %>

app/views/advertisements/_info_window.html.erb
<h2 class= ><%= advertisement.title %></h2>
<p><%= advertisement.description %></p>
<p><%= advertisement.address %></p>
<p><%= advertisement.price %> €</p>

app/views/advertisements/_marker.html.erb
<%= image_tag "friends.png", height: 30, width: 30, alt: "Friends" %>

app/views/advertisements/index.html.erb
<section class="service">
<div class="cards">
<div class="service-left">
<p class="title">Notre Service</p>
<p class="text">Bienvenue sur Make Friends, là où rencontrer des gens pour s'amuser n'a jamais été aussi facile ! <br> <br>
Nous savons que l'amitié est précieuse, c'est pourquoi nous vous offrons la possibilité de créer des liens et de vivre des moments inoubliables avec de véritables amis, sans les contraintes de l'engagement à long terme</p>
</div>
<div class="service-right">
  <%= image_tag "photo-1543807535-eceef0bc6599.avif" %>
</div>
</div>
</section>
<%# section histoire %>
<section class="histoire">
<div class="cards">
<div class="histoire-right">
  <%= image_tag "photo-1511376979163-f804dff7ad7b.avif" %>
</div>
<div class="histoire-left">
  <p class="title">Notre Histoire</p>
  <p class="text">Make Friends a été créé avec une vision simple : rendre l'amitié accessible à tous <br><br>
    Nous avons été inspiré par l'idée qu'il est parfois difficile de trouver des amis pour partager des activités, discuter ou simplement passer du temps de qualité. Il a compris que de nombreuses personnes traversent des périodes de solitude et de déconnexion, même au sein de sociétés de plus en plus connectées. <br><br>
    C'est pourquoi Make Friends a vu le jour, avec pour objectif de faire de l'amitié une expérience accessible à tout moment. Nous croyons que l'amitié n'a pas besoin d'être compliquée, qu'elle peut être fluide et adaptée à vos besoins.</p>
</div>
</div>
<%# section engagemant %>
</section>
<section class="engagemant">
<div class="title-engagement">Notre engagement</div>
<div class="cards">
<div class="eng-right">
  <%= image_tag "photo-1600880292089-90a7e086ee0c.avif" %>
</div>
<div class="eng-left">
  <p class="text">Chez Make Friends, nous nous engageons à créer un environnement sécurisé et respectueux pour tous nos utilisateurs. <br><br>
  Chaque ami disponible à la location est soigneusement vérifié et noté par notre communauté, garantissant ainsi des interactions positives et agréables. Nous promouvons la diversité, l'inclusion et le respect mutuel au sein de notre communauté.</p>
</div>
</div>
</section>
<%# section offre  %>
<section class="offre">
<div class="title-offre">Notre offre</div>
<div class="cards">
<div class="offre-right">
  <%= image_tag "loonapix_1700817097349732546.png" %>
</div>
<div class="offre-left">
<div class="title-of">Une compagnie instantanée</div>
<p class="text">Louer un ami permet d'avoir de la compagnie <br> instantanée pour des événements, des sorties <br> ou simplement pour discuter. Cela peut être <br> particulièrement bénéfique pour les personnes <br> qui se sentent seules ou qui souhaitent <br> rencontrer de nouvelles personnes.</p>
</div>
</div>
<div class="cards">
<div class="offre-right">
  <%= image_tag "loonapix_170081704628459202.png" %>
</div>
<div class="offre-left">
<div class="title-of">Confidence & conseils</div>
<p class="text">Un ami de location peut être une oreille <br> attentive et bienveillante, prête à écouter vos <br> préoccupations et à vous donner des conseils <br> impartiaux. C'est une opportunité d'exprimer <br> ses pensées et ses émotions en toute confiance.</p>
</div>
</div>
<div class="cards">
<div class="offre-right">
  <%= image_tag "loonapix_17008169273227967720.png" %>
</div>
<div class="offre-left">
<div class="title-of">Expérience Sociale</div>
<p class="text">Si vous participez à des événements sociaux <br> ou à des activités où vous ne connaissez <br> personne, avoir un ami de location peut vous <br>  aider à vous sentir plus à l'aise et à vous <br> intégrer plus facilement dans le groupe.</p>
</div>
</div>
</section>
 <%# card  %>


<%# A GARDER %>
<div class="advertisements-container">
  <% @advertisements.each do |advertisement| %>
    <%= link_to advertisement_path(advertisement) do %>
    <div class="card">
      <% if advertisement.photo.attached? %>
        <%= link_to advertisement_path(advertisement) do %>
          <div class="card-image">
            <%= cl_image_tag advertisement.photo.key, width: 280, height: 100, crop: :fill, class: "image-style" %>
          </div>
        <% end %>
      <% end %>
      <p><%= advertisement.title %></p>
      <p><%= advertisement.description %></p>
      <p><%= advertisement.price %></p>
      <%= link_to "Réserver", new_advertisement_booking_path(advertisement), method: :delete, data: { confirm: "Êtes-vous sûr de vouloir supprimer cette annonce?" }, class: "btn btn-outline-dark m-3" %>
    </div>
  <% end %>
<% end %>
</div>
<%= link_to "Créer une annonce", new_advertisement_path(@advertisement), class: "btn btn-outline-dark m-3" %>

<div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

<footer class="footer">
<div class="footer-title">Suivez nous !</div>
<div class="footer-text">Actuellement le service n'est disponible que sur Paris et <br> en région parisienne , il serra bientôt disponible dans <br> toute la France !</div>
<div class="menu">
<div><i class="fa-brands fa-facebook"></i></div>
<div><i class="fa-brands fa-instagram"></i></div>
<div><i class="fa-solid fa-x"></i></div>
</div>
<div class="copy">© 2023 Tous droits réservés par Make Friends</div>
</footer>

app/views/advertisements/new.html.erb
<h1>Nouvelle annonce</h1>
<%= render 'form' %>

app/views/advertisements/show.html.erb
<div class="adver">
<div class="cards-advertisement">
<% if @advertisement.photo.attached? %>
<div class="card-left">
  <%= link_to advertisement_path(@advertisement) do %>
      <div class="image-container">
        <%= cl_image_tag @advertisement.photo.key, width: 400, height: 300, crop: :fill, class: "advertisement-image" %>
      </div>
    <% end %>
</div>
  <% end %>
  <div class="card-right">
   <h1><%= @advertisement.title %></h1>
  <p class="description"><%= @advertisement.description %></p>

  <p class="price"> <span>Prix :</span> <%= @advertisement.price %> €</p>

  <p class="Adresse"><%= @advertisement.address %></p>
  <%= link_to "Réserver", new_advertisement_booking_path(@advertisement), class: "btn btn-outline-dark m-3" %>
  </div>


</div>
</div>
<div class="adver">
<%= link_to "Return to advertisements", advertisements_path(@advertisement), class: "btn btn-outline-dark m-3" %>
</div>
<footer class="footer">

<div class="footer-title">Suivez nous !</div>
<div class="footer-text">Actuellement le service n'est disponible que sur Paris et <br> en région parisienne , il serra bientôt disponible dans <br> toute la France !</div>
<div class="menu">
<div><i class="fa-brands fa-facebook"></i></div>
<div><i class="fa-brands fa-instagram"></i></div>
<div><i class="fa-solid fa-x"></i></div>
</div>

<div class="copy">© 2023 Tous droits réservés par Make Friends</div>
</footer>

app/views/bookings/_form.html.erb
<%= simple_form_for [@advertisement, @booking] do |form| %>
  <%= form.input :status, label: "Status", as: :select, collection: Booking::STATUSES %>
  <%= form.submit "Faire une réservation" %>
<% end %>

app/views/bookings/new.html.erb
<h1>Nouvelle réservation</h1>
<%= render 'form' %>
<div>

app/views/bookings/show.html.erb
<h1><%= @booking.status %></h1>
<p>Description: <%= @booking.total_price %></p>

app/views/dashboards/_modal.html.erb
<div class="modal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Confirmation</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>Etes-vous sûr de vouloir supprimer cette annonce ?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
        <button type="button" class="btn btn-primary">Sauvegarder les modifications</button>
      </div>
    </div>
  </div>
</div>

app/views/dashboards/edit.html.erb
<h1>Modifier l'annonce</h1>
<%= form_with(model: @advertisement, url: advertisement_path(@advertisement), method: :patch, local: true) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, autofocus: true %>
  </div>
  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
    <div class="field">
    <%= form.label :price %>
    <%= form.text_area :price %>
  </div>
  <div class="actions">
    <%= form.submit "Edite" %>
  </div>
<% end %>
<%= link_to "Retour à la liste des annonces", advertisements_path %>

app/views/dashboards/index.html.erb
<h1>MES ANNONCES</h1>

<h2>Les annonces que j'ai sélectionnée</h2>
<div class="card-container">
  <% @advertisements.each do |advertisement| %>
    <div class="card">
      <% if advertisement.photo.attached? %>
        <%= link_to advertisement_path(advertisement) do %>
          <div class="card-image">
            <%= cl_image_tag advertisement.photo.key, width: 280, height: 100, crop: :fill, class: "image-style" %>
          </div>
        <% end %>
      <% end %>
      <p><%= advertisement.title %></p>
      <p><%= advertisement.description %></p>
      <p><%= advertisement.price %></p>
      <%= button_to "Supprimer", advertisement_path(advertisement), method: :delete %>
    </div>
    <div>
      <%= link_to "Update", update_path %>
      </div>
  <% end %>
</div>

<h2>Les annonces que j'ai crées</h2>
<div class="card-container">
  <% @advertisements.each do |advertisement| %>
    <div class="card">
      <% if advertisement.photo.attached? %>
        <%= link_to advertisement_path(advertisement) do %>
          <div class="card-image">
            <%= cl_image_tag advertisement.photo.key, width: 280, height: 100, crop: :fill, class: "image-style" %>
          </div>
        <% end %>
      <% end %>
      <p><%= advertisement.title %></p>
      <p><%= advertisement.description %></p>
      <p><%= advertisement.price %></p>
      <%= button_to "Supprimer", advertisement_path(advertisement), method: :delete %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MakeFriends</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.css" type="text/css">
    <%= javascript_importmap_tags %>


  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/banner" %>
    <div class="container">
    <%= yield %>

      <%= render "shared/flashes" %>
    </div>
  </body>
</html>

app/views/pages/dashboard.html.erb
<%= link_to "Revenir aux annonces", advertisements_path(@advertisement), class: "btn btn-outline-dark m-3" %>
<h2>Mes réservations</h2>
<div class="card-container-res">
  <% @advertisements.each do |advertisement| %>
    <div class="card">
      <% if advertisement.photo.attached? %>
        <%= link_to advertisement_path(advertisement) do %>
          <div class="card-image">
            <%= cl_image_tag advertisement.photo.key, width: 280, height: 100, crop: :fill, class: "image-style" %>
          </div>
        <% end %>
      <% end %>
      <p><%= advertisement.title %></p>
      <p><%= advertisement.description %></p>
      <p>Prix : <%= advertisement.price %> €</p> 
      <%= button_to "Supprimer", advertisement_path(advertisement), method: :delete %>
    </div>
  <% end %>
</div>

<h2>Mes annonces</h2>
<div class="card-container">
  <% @my_advertisements.each do |advertisement| %>
    <div class="card">
      <% if advertisement.photo.attached? %>
        <%= link_to advertisement_path(advertisement) do %>
          <div class="card-image">
            <%= cl_image_tag advertisement.photo.key, width: 280, height: 100, crop: :fill, class: "image-style" %>
          </div>
        <% end %>
      <% end %>
      <p><%= advertisement.title %></p>
      <p><%= advertisement.description %></p>
      <p>Prix : <%= advertisement.price %> €</p>
       <% advertisement.bookings.each do |booking| %>
        <%= booking.total_price %>
      <% end %>
      <%= button_to "Supprimer", advertisement_path(advertisement), method: :delete %>
    </div>
  <% end %>
</div>
<style>
.card-container {
  display: flex;
  flex-wrap: wrap;
}
.card {
  width: 400px;
  margin: 15px;
  padding: 10px;
  border: 1px solid #ddd;
  border-radius: 5px;
  background-color: #fff;
}
.card-image {
  width: 100%;
  height: 150px;
  overflow: hidden;
  border-radius: 5px;
}
.image-style {
  width: 100%;
  height: 100%;
  object-fit: cover;
}
</style>

app/views/pages/home.html.erb
<h1>Hello !</h1>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://img.grouponcdn.com/seocms/NAYfSQJQqUfnqfRsrT5kDkNmHRN/Friends-taking-cooking-class-together-1-768x461_jpg-768x461);">
  <div class="container">
    <h1>Make Friends <strong>l'inconnue</strong> mène toujours<strong> aux belles rencontres</strong>!</h1>
    <p>Rencontrez et partagez avec des gens des expériences hors du commun.</p>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to advertisements_path(@advertisement), class: "navbar-brand" do %>
      <%= image_tag "logo_make-friends.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Accueil", dashboard_path(@dashboard), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Créer une annonce", new_advertisement_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://avatars.githubusercontent.com/u/145803681?v=4", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Annonces", advertisements_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>